/**
 * Evolution Engine - 进化引擎
 */

import { execSync } from 'child_process';
import * as path from 'path';
import type {
  EnvFingerprint,
  EvolutionConfig,
  EvolutionEvent,
  Gene,
  Capsule,
  OutcomeStatus,
  Signal
} from '../types/gene-capsule-schema';
import { extractSignals } from './signal-extractor';
import { selectGene, banGenesFromFailedCapsules, NoMatchingGeneError, AllGenesBannedError } from './gene-selector';
import { selectCapsule, shouldReuseCapsule, updateCapsuleFeedback } from './capsule-manager';
import {
  estimateBlastRadius,
  requiresApproval,
  executeValidation,
  checkPathSafety,
  isValidationCommandAllowed,
  type BlastRadiusEstimate
} from './validation-gate';
import { LLMProvider } from './llm-provider';
import { buildAutoGene } from './auto-gene-builder';
import { applyEpigeneticMarks } from './epigenetic';
import { shouldDistill, prepareDistillation, completeDistillation, type DistillationState } from './skill-distiller';
import type { CapsuleStore } from '../storage/capsule-store';
import type { GeneStore } from '../storage/gene-store';

export interface EvolutionEngineConfig extends EvolutionConfig {
  llmProvider?: 'openai' | 'anthropic' | 'local';
  llmModel?: string;
  llmApiKey?: string;
  llmBaseURL?: string;

  /**
   * @planned — 回滚能力，预留接口，当前版本未实现。
   * 计划在 v2.0 中支持进化失败后自动 git revert 或文件级还原。
   */
  rollbackEnabled?: boolean;
  /** @planned — 回滚策略，依赖 rollbackEnabled，当前未实现 */
  rollbackStrategy?: 'full' | 'partial' | 'none';

  /**
   * @planned — 基因/胶囊选择结果缓存，当前版本未实现。
   * 计划在高频调用场景下缓存 selectGene / selectCapsule 结果以提升性能。
   */
  cacheEnabled?: boolean;
  /** @planned — 缓存 TTL（毫秒），依赖 cacheEnabled，当前未实现 */
  cacheTtlMs?: number;
}

export interface EvolutionChange {
  file: string;
  operation: 'create' | 'modify' | 'delete';
  content: string;
  reasoning: string;
}

export interface EvolutionState {
  sessionId: string;
  iteration: number;
  signals: Signal[];
  selectedGene: Gene | null;
  selectedCapsule: Capsule | null;
  changes: EvolutionChange[];
  validationPassed: boolean;
  startTime: number;
  endTime?: number;
}

export interface EvolutionResult {
  event: EvolutionEvent;
  changes: EvolutionChange[];
  capsule_created: string | null;
  auto_gene_created?: boolean;
  distillation_triggered?: boolean;
  distilled_gene_id?: string | null;
}

interface EvolutionExecution {
  changes: EvolutionChange[];
  confidence: number;
}

interface ValidationCheckResult {
  passed: boolean;
  errors: string[];
  warnings: string[];
  commandsRun: number;
}

export class LLMProviderError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = 'LLMProviderError';
  }
}

export interface ApprovalContext {
  signals: Signal[];
  geneId: string;
  capsuleId?: string;
  confidence: number;
  autoGenerated: boolean;
}

export class ApprovalRequiredError extends Error {
  constructor(
    public readonly blastRadius: BlastRadiusEstimate,
    public readonly pendingChanges: EvolutionChange[],
    public readonly context?: ApprovalContext
  ) {
    super(`Approval required: ${blastRadius.riskLevel} risk level`);
    this.name = 'ApprovalRequiredError';
  }
}

export class EvolutionEngine {
  private state: EvolutionState;
  private genePool: Gene[] = [];
  private capsulePool: Capsule[] = [];
  private llmProvider?: LLMProvider;
  private failedCapsules: Array<{ gene: string; trigger: Signal[] }> = [];
  private distillationState: DistillationState = { lastDistillationTime: 0 };

  constructor(
    private config: EvolutionEngineConfig,
    private eventLogger: EventLogger,
    private capsuleStore?: CapsuleStore,
    private geneStore?: GeneStore
  ) {
    this.state = {
      sessionId: config.session_scope || `session_${Date.now()}`,
      iteration: 0,
      signals: [],
      selectedGene: null,
      selectedCapsule: null,
      changes: [],
      validationPassed: false,
      startTime: Date.now()
    };

    if (config.llmProvider && config.llmModel) {
      const apiKey = process.env.LLM_API_KEY || process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY || config.llmApiKey;
      this.llmProvider = new LLMProvider({
        provider: config.llmProvider,
        model: config.llmModel,
        apiKey,
        baseURL: config.llmBaseURL
      });
      delete this.config.llmApiKey;
    }
  }

  setGenePool(genes: Gene[]): void {
    this.genePool = genes;
  }

  setCapsulePool(capsules: Capsule[]): void {
    this.capsulePool = capsules;
  }

  async evolve(
    logs: any[],
    overrides?: { dryRun?: boolean; strategy?: string }
  ): Promise<EvolutionResult> {
    const savedDryRun = this.config.dryRun;
    const savedStrategy = this.config.strategy;
    if (overrides?.dryRun !== undefined) this.config.dryRun = overrides.dryRun;
    if (overrides?.strategy !== undefined) this.config.strategy = overrides.strategy as EvolutionConfig['strategy'];

    this.state.iteration += 1;
    this.state.startTime = Date.now();

    try {
      const { prioritySignals } = extractSignals({ logs: logs as any });
      this.state.signals = prioritySignals;

      const { selected: gene, alternatives, autoGenerated } = this.selectGeneWithFallback();
      this.state.selectedGene = gene;

      const capsule = this.selectCapsule();
      this.state.selectedCapsule = capsule;

      const envFingerprint = this.getEnvFingerprint();
      const reuseDecision = capsule ? shouldReuseCapsule(capsule, this.state.signals, envFingerprint) : null;
      const basePrompt = this.buildEvolutionPrompt({
        signals: this.state.signals,
        gene,
        capsule,
        shouldReuse: reuseDecision,
        alternatives
      });

      let execution = await this.executeEvolution(basePrompt);
      let blastRadius = this.estimateBlastRadius(execution.changes);
      const approvalCtx: ApprovalContext = {
        signals: this.state.signals,
        geneId: gene.id,
        capsuleId: capsule?.id,
        confidence: execution.confidence,
        autoGenerated
      };
      this.ensureApproval(blastRadius, execution.changes, approvalCtx);

      let validation = await this.validateChanges(gene, execution.changes);
      if (!validation.passed && this.llmProvider && execution.changes.length > 0) {
        const retryPrompt = this.buildRetryPrompt(basePrompt, validation.errors);
        execution = await this.executeEvolution(retryPrompt);
        blastRadius = this.estimateBlastRadius(execution.changes);
        approvalCtx.confidence = execution.confidence;
        this.ensureApproval(blastRadius, execution.changes, approvalCtx);
        validation = await this.validateChanges(gene, execution.changes);
      }

      this.state.changes = execution.changes;
      this.state.validationPassed = validation.passed;

      const outcomeStatus: OutcomeStatus = validation.passed ? 'success' : 'failed';
      const outcomeScore = this.computeOutcomeScore({
        validationPassed: validation.passed,
        llmConfidence: execution.confidence,
        blastRadius,
        capsuleReused: Boolean(capsule && reuseDecision?.shouldReuse)
      });

      const event = this.buildEvolutionEvent({
        gene,
        capsule,
        changes: execution.changes,
        blastRadius,
        validation,
        outcomeScore
      });
      await this.eventLogger.append(event);

      const capsuleCreated = validation.passed
        ? await this.persistSuccessfulCapsule(gene, execution.changes, this.state.signals, outcomeScore, capsule)
        : null;

      applyEpigeneticMarks(gene, envFingerprint, outcomeStatus);

      if (capsule && this.capsuleStore) {
        const updatedCapsule = updateCapsuleFeedback(capsule, outcomeStatus, outcomeScore);
        await this.capsuleStore.update(updatedCapsule);
        this.capsulePool = this.capsulePool.map(candidate => candidate.id === updatedCapsule.id ? updatedCapsule : candidate);
      }

      if (this.geneStore) {
        await this.geneStore.upsert(gene);
        if (autoGenerated && !this.genePool.some(candidate => candidate.id === gene.id)) {
          this.genePool.push(gene);
        }
      }

      const distillResult = validation.passed
        ? await this.tryDistillation()
        : { triggered: false, geneId: null };

      this.state.endTime = Date.now();
      return {
        event,
        changes: execution.changes,
        capsule_created: capsuleCreated,
        auto_gene_created: autoGenerated,
        distillation_triggered: distillResult.triggered,
        distilled_gene_id: distillResult.geneId
      };
    } catch (error) {
      if (!(error instanceof ApprovalRequiredError) && this.state.selectedGene) {
        this.failedCapsules.push({
          gene: this.state.selectedGene.id,
          trigger: this.state.signals
        });
      }

      if (!(error instanceof ApprovalRequiredError)) {
        const errorEvent = this.buildErrorEvent(error as Error);
        await this.eventLogger.append(errorEvent);
      }
      throw error;
    } finally {
      this.config.dryRun = savedDryRun;
      this.config.strategy = savedStrategy;
    }
  }

  private selectGeneWithFallback(): { selected: Gene; alternatives: Gene[]; autoGenerated: boolean } {
    const bannedGeneIds = banGenesFromFailedCapsules(this.failedCapsules, this.genePool);
    const selectionOptions = {
      ...this.config.selection,
      bannedGeneIds,
      envFingerprint: this.getEnvFingerprint()
    };

    try {
      const result = selectGene(this.genePool, this.state.signals, selectionOptions);
      return { ...result, autoGenerated: false };
    } catch (error) {
      if (error instanceof NoMatchingGeneError || error instanceof AllGenesBannedError) {
        const autoGene = buildAutoGene({ signals: this.state.signals });
        return { selected: autoGene, alternatives: [], autoGenerated: true };
      }
      throw error;
    }
  }

  private selectCapsule(): Capsule | null {
    return selectCapsule(this.capsulePool, this.state.signals, this.getEnvFingerprint()) || null;
  }

  private buildEvolutionPrompt(opts: {
    signals: Signal[];
    gene: Gene;
    capsule: Capsule | null;
    shouldReuse: ReturnType<typeof shouldReuseCapsule> | null;
    alternatives: Gene[];
  }): string {
    const { signals, gene, capsule, shouldReuse, alternatives } = opts;
    let prompt = '# Evolution Task\n\n';
    prompt += `## Detected Signals\n${signals.slice(0, 10).join(', ')}\n\n`;
    prompt += `## Selected Gene: ${gene.id}\n`;
    prompt += `Category: ${gene.category}\n`;
    prompt += `Strategy:\n${gene.strategy.map(step => `- ${step}`).join('\n')}\n\n`;
    prompt += '## Constraints\n';
    prompt += `Max files: ${gene.constraints.max_files || 'unlimited'}\n`;
    prompt += `Max lines: ${gene.constraints.max_lines || 'unlimited'}\n`;
    if (gene.constraints.forbidden_paths) prompt += `Forbidden: ${gene.constraints.forbidden_paths.join(', ')}\n`;
    prompt += '\n';

    if (capsule) {
      prompt += '## Similar Capsule Available\n';
      prompt += `ID: ${capsule.id}\n`;
      prompt += `Summary: ${capsule.summary}\n`;
      prompt += `Confidence: ${capsule.confidence}\n`;
      prompt += `Outcome: ${capsule.outcome.status} (score: ${capsule.outcome.score})\n`;
      if (shouldReuse?.shouldReuse) {
        prompt += `\n**RECOMMENDATION: Reuse this capsule**\nReason: ${shouldReuse.reason}\n`;
      }
      prompt += '\n';
    }

    if (alternatives.length > 0) {
      prompt += '## Alternative Genes\n';
      alternatives.forEach((alternative, index) => {
        prompt += `${index + 1}. ${alternative.id} (${alternative.category})\n`;
      });
      prompt += '\n';
    }

    prompt += '## Task\n';
    prompt += 'Based on the signals and selected gene strategy, generate the necessary code changes.\n';
    prompt += 'Follow the constraints strictly.\n';
    prompt += 'If a similar capsule exists and is recommended for reuse, prefer reusing it.\n';
    return prompt.trim();
  }

  private buildRetryPrompt(prompt: string, validationErrors: string[]): string {
    return `${prompt}\n\n## Validation Feedback\n${validationErrors.map(error => `- ${error}`).join('\n')}\n\nRegenerate a smaller, safer patch that satisfies validation.`;
  }

  private async executeEvolution(prompt: string): Promise<EvolutionExecution> {
    if (!this.llmProvider) {
      return { changes: [], confidence: 0.8 };
    }

    try {
      const output = await this.llmProvider.generateEvolution(prompt);
      if (this.config.dryRun) {
        console.log('[DryRun] Would apply changes:', output.changes.map(change => `${change.operation} ${change.file}`));
      }
      return {
        changes: output.changes,
        confidence: output.confidence ?? 0.75
      };
    } catch (error) {
      throw new LLMProviderError(`LLM generation failed: ${(error as Error).message || 'Unknown error'}`, error);
    }
  }

  private estimateBlastRadius(changes: EvolutionChange[]): BlastRadiusEstimate {
    const linesPerFile = new Map<string, number>();
    changes.forEach(change => linesPerFile.set(change.file, change.content.split('\n').length));
    return estimateBlastRadius(changes.map(change => change.file), linesPerFile, this.config.forbidden_paths);
  }

  private ensureApproval(
    blastRadius: BlastRadiusEstimate,
    changes: EvolutionChange[],
    approvalContext?: ApprovalContext
  ): void {
    const needsApproval = requiresApproval(blastRadius, {
      reviewMode: this.config.review_mode,
      maxBlastRadius: this.config.max_blast_radius,
      autoApproveLowRisk: this.config.autoApproveLowRisk ?? false,
      autoApproveMediumRisk: this.config.autoApproveMediumRisk ?? false
    });

    if (needsApproval) {
      throw new ApprovalRequiredError(blastRadius, changes, approvalContext);
    }
  }

  private async validateChanges(gene: Gene, changes: EvolutionChange[]): Promise<ValidationCheckResult> {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (gene.validation?.some(command => !isValidationCommandAllowed(command))) {
      errors.push('Validation command rejected by security policy');
      return { passed: false, errors, warnings, commandsRun: gene.validation?.length || 0 };
    }

    const pathCheck = checkPathSafety(changes.map(change => change.file), process.cwd(), this.config.forbidden_paths);
    errors.push(...pathCheck.violations);
    warnings.push(...pathCheck.warnings);
    if (!pathCheck.safe) {
      return { passed: false, errors, warnings, commandsRun: gene.validation?.length || 0 };
    }

    if (gene.validation && gene.validation.length > 0) {
      const validation = await executeValidation(gene.validation, {
        timeoutMs: 30000,
        maxConcurrent: 3,
        failFast: false
      });

      validation.failures.forEach(failure => errors.push(failure.error));
      return {
        passed: validation.passed,
        errors,
        warnings,
        commandsRun: validation.commandsRun
      };
    }

    return { passed: true, errors, warnings, commandsRun: 0 };
  }

  private computeOutcomeScore(opts: {
    validationPassed: boolean;
    llmConfidence: number;
    blastRadius: BlastRadiusEstimate;
    capsuleReused: boolean;
  }): number {
    if (!opts.validationPassed) {
      return 0;
    }

    const baseConfidence = Math.max(0, Math.min(1, opts.llmConfidence || 0.75));
    const validationScore = 1;
    const blastPenalty = opts.blastRadius.riskLevel === 'critical'
      ? 0.3
      : opts.blastRadius.riskLevel === 'high'
        ? 0.15
        : opts.blastRadius.riskLevel === 'medium'
          ? 0.05
          : 0;
    const reuseBonus = opts.capsuleReused ? 0.03 : 0;

    const score = (baseConfidence * 0.6) + (validationScore * 0.4) - blastPenalty + reuseBonus;
    return Number(Math.max(0, Math.min(0.95, score)).toFixed(4));
  }

  private buildEvolutionEvent(opts: {
    gene: Gene;
    capsule: Capsule | null;
    changes: EvolutionChange[];
    blastRadius: BlastRadiusEstimate;
    validation: ValidationCheckResult;
    outcomeScore: number;
  }): EvolutionEvent {
    const { gene, capsule, changes, blastRadius, validation, outcomeScore } = opts;
    const totalLinesAdded = changes.reduce((sum, change) => sum + change.content.split('\n').length, 0);
    return {
      id: `event_${Date.now()}_${this.state.iteration}`,
      timestamp: new Date().toISOString(),
      signals: this.state.signals,
      selected_gene: gene.id,
      used_capsule: capsule?.id,
      outcome: {
        status: validation.passed ? 'success' : 'failed',
        score: outcomeScore,
        changes: {
          files_modified: changes.length,
          lines_added: totalLinesAdded,
          lines_removed: changes.filter(change => change.operation === 'delete').reduce((sum, change) => sum + change.content.split('\n').length, 0)
        }
      },
      validation: {
        passed: validation.passed,
        commands_run: validation.commandsRun,
        errors: validation.errors.length > 0 ? validation.errors : undefined
      },
      metadata: {
        session_id: this.state.sessionId,
        iteration: this.state.iteration,
        blast_radius: {
          files: blastRadius.files,
          lines: blastRadius.lines,
          risk_level: blastRadius.riskLevel
        },
        warnings: validation.warnings
      }
    };
  }

  private buildErrorEvent(error: Error): EvolutionEvent {
    return {
      id: `event_error_${Date.now()}`,
      timestamp: new Date().toISOString(),
      signals: this.state.signals,
      selected_gene: this.state.selectedGene?.id || 'unknown',
      outcome: {
        status: 'failed',
        score: 0,
        changes: { files_modified: 0, lines_added: 0, lines_removed: 0 }
      },
      validation: {
        passed: false,
        commands_run: 0,
        errors: [error.message]
      },
      metadata: {
        session_id: this.state.sessionId,
        iteration: this.state.iteration,
        error: error.message
      }
    };
  }

  private async tryDistillation(): Promise<{ triggered: boolean; geneId: string | null }> {
    if (!this.geneStore || !this.capsuleStore || !this.llmProvider) {
      return { triggered: false, geneId: null };
    }

    if (!shouldDistill(this.capsulePool, this.distillationState)) {
      return { triggered: false, geneId: null };
    }

    try {
      const outputDir = path.join(process.cwd(), '.evomap', 'distillation');
      const request = await prepareDistillation(
        this.capsulePool,
        this.genePool,
        outputDir,
        { state: this.distillationState }
      );
      if (!request) {
        return { triggered: false, geneId: null };
      }

      const { readFile } = await import('fs/promises');
      const prompt = await readFile(request.promptFilePath, 'utf-8');
      const llmResponse = await this.llmProvider.generateText(prompt);

      const sourceCapsuleIds = this.capsulePool
        .filter(c => c.outcome.status === 'success' && !c._deleted)
        .slice(-20)
        .map(c => c.id);

      const result = completeDistillation(llmResponse.text, this.genePool, sourceCapsuleIds);
      if (result.success && result.gene) {
        await this.geneStore.upsert(result.gene);
        this.genePool.push(result.gene);
        return { triggered: true, geneId: result.gene.id };
      }

      return { triggered: true, geneId: null };
    } catch (error) {
      console.warn('[EvolutionEngine] Distillation failed (non-fatal):', (error as Error).message);
      return { triggered: true, geneId: null };
    }
  }

  private async persistSuccessfulCapsule(
    gene: Gene,
    changes: EvolutionChange[],
    signals: Signal[],
    outcomeScore: number,
    reusedCapsule: Capsule | null
  ): Promise<string | null> {
    if (reusedCapsule) {
      return reusedCapsule.id;
    }

    const capsule: Capsule = {
      type: 'Capsule',
      schema_version: '1.5.0',
      id: `capsule_${Date.now()}`,
      trigger: [...signals],
      gene: gene.id,
      summary: 'Auto-generated from successful evolution',
      confidence: Math.max(0.7, outcomeScore),
      blast_radius: {
        files: changes.length,
        lines: changes.reduce((sum, change) => sum + change.content.split('\n').length, 0)
      },
      outcome: {
        status: 'success',
        score: outcomeScore
      },
      env_fingerprint: this.getEnvFingerprint(),
      metadata: {
        created_at: new Date().toISOString(),
        source: 'local',
        validated: true
      }
    };

    if (!this.capsuleStore) {
      return null;
    }

    await this.capsuleStore.add(capsule);
    this.capsulePool.push(capsule);
    return capsule.id;
  }

  private getEnvFingerprint(): EnvFingerprint {
    return {
      node_version: process.version,
      platform: process.platform as EnvFingerprint['platform'],
      arch: process.arch as EnvFingerprint['arch'],
      working_dir: process.cwd(),
      git_branch: this.getGitBranch()
    };
  }

  private getGitBranch(): string | undefined {
    try {
      return execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
    } catch {
      return undefined;
    }
  }

  getState(): EvolutionState {
    return { ...this.state };
  }
}

export interface EventLogger {
  append(event: EvolutionEvent): Promise<void>;
  getAll(): Promise<EvolutionEvent[]>;
  getBySession(sessionId: string): Promise<EvolutionEvent[]>;
  getRecent(count: number): Promise<EvolutionEvent[]>;
}
